In [1]:
import numpy as np

In [7]:
print(np.__version__)

1.16.2


In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
data1=np.zeros(5)
size=data1.size*data1.itemsize
print("%d bytes"% size)

40 bytes


In [10]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [11]:
data2=np.zeros(10)
data2[4]=1
print(data2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
data3=np.arange(10,50)
print(data3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
data4=data3[::-1]
print(data4)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [14]:
data5=np.arange(0,9)
data5=data5.reshape(3,3)
print(data5)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
n=np.nonzero([1,2,0,0,4,0])
print(n)

(array([0, 1, 4], dtype=int64),)


In [16]:
data6=np.eye(3)
print(data6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
data7=np.random.random((3,3,3))
print(data7)

[[[0.88836865 0.74923593 0.98686662]
  [0.91824259 0.43003068 0.16948376]
  [0.7441283  0.03217326 0.76228266]]

 [[0.5975055  0.33817074 0.22428973]
  [0.13683104 0.91861345 0.60364838]
  [0.3558403  0.73724313 0.48681469]]

 [[0.22452693 0.35736937 0.58387597]
  [0.72643154 0.39570504 0.36990371]
  [0.51165116 0.612159   0.16474823]]]


In [18]:
data8=np.random.random((10,10))
data8_min=data8.min()
data8_max=data8.max()
print(data8_min)
print(data8_max)

0.00032654276090571255
0.9723801364672465


In [19]:
data9=np.random.random(30)
data9_mean=data9.mean()
print(data9_mean)

0.5064078733293719


In [20]:
data10=np.ones((5,5))
data10[1:-1,1:-1]=0
print(data10)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
data11=np.pad(data8,pad_width=1,mode='constant',constant_values=0)
print(data11)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.94866472e-01 9.43315791e-02 8.44246216e-01
  7.71731131e-02 6.12881265e-01 2.14407573e-01 5.11537451e-01
  5.88810579e-01 7.44567355e-01 4.24420428e-01 0.00000000e+00]
 [0.00000000e+00 7.69821024e-01 5.17292490e-01 5.61184325e-01
  8.36840998e-01 3.40629630e-01 2.64602107e-01 4.89262670e-01
  2.15229863e-01 4.34262240e-01 1.46297261e-01 0.00000000e+00]
 [0.00000000e+00 1.12418777e-01 3.79327421e-01 2.53246330e-02
  3.63219244e-01 7.23077141e-01 3.39526907e-01 8.31770486e-01
  5.91178807e-01 3.93910806e-01 4.20736434e-01 0.00000000e+00]
 [0.00000000e+00 8.59874609e-01 4.24654614e-01 5.50707140e-01
  1.12794384e-01 9.72380136e-01 2.88477752e-01 8.42703385e-02
  3.04407649e-01 6.30712093e-02 7.01371866e-01 0.00000000e+00]
 [0.00000000e+00 2.62687497e-01 4.39053672e-01 1.37141238e-01
  5

In [22]:
data12=np.nan
print(data12)
print(0*np.nan)
print(np.nan==np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)

nan
nan
False
nan
False


In [23]:
data13=np.diag(1+np.arange(4),k=-1)  ##这里k=-1,相当于对角线的值向下平移一个单位
print(data13)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [24]:
data14=np.zeros((8,8),dtype=int)
data14[1::2,::2]=1
data14[::2,1::2]=1
print(data14)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [25]:
data15=np.random.random((6,7,8))
print(data15)
print(np.unravel_index(10,(6,7,8)))

[[[6.85583884e-01 6.67402822e-01 1.77735789e-01 5.75888535e-01
   2.37270875e-01 2.76364814e-01 3.41472997e-01 7.36387132e-01]
  [1.41845070e-01 2.01808706e-01 3.54756798e-01 7.84250140e-02
   5.73020805e-01 7.75715386e-01 2.56657658e-01 1.38210221e-01]
  [8.50422078e-01 8.88368165e-01 7.27490873e-01 2.22587175e-02
   4.30815741e-01 8.45111541e-01 1.94198927e-01 3.44575472e-01]
  [6.58489987e-01 4.38023338e-01 7.33066656e-04 4.03661856e-01
   7.48498782e-02 8.32040665e-01 5.24390569e-01 4.72325074e-01]
  [3.56607540e-01 7.72876698e-02 3.72995252e-01 3.57426664e-01
   5.46129375e-01 3.79117875e-01 6.31685041e-01 3.60168924e-02]
  [3.78699649e-01 3.29794088e-01 2.36798992e-01 4.30713752e-01
   8.32522225e-01 8.21715019e-01 3.73826656e-01 6.75925160e-01]
  [1.05921420e-01 1.68062062e-01 5.39072778e-01 4.13087963e-01
   3.26748251e-01 3.41901627e-01 9.66652716e-02 2.60066306e-01]]

 [[4.36091684e-01 8.85655707e-01 9.46156282e-02 1.32144402e-01
   3.83647440e-01 1.04105108e-01 7.42709532e-0

In [26]:
data16=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(data16)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [27]:
data17=np.random.random((5,5))
data17_min,data17_max=data17.min(),data17.max()
data17_normal=(data17-data17_min)/(data17_max-data17_min)
print(data17_normal)

[[0.69260252 0.94460147 0.13408655 0.21050972 0.05569189]
 [0.34751509 0.94278717 0.44530239 0.6497592  0.95454704]
 [0.05247379 0.60993657 0.85042294 0.05862845 0.17978379]
 [0.         0.57535034 0.80551787 0.1640576  0.24838351]
 [0.89514974 0.01294938 1.         0.09993358 0.88083738]]


In [28]:
color=np.dtype([('R',np.ubyte,1),
               ('G',np.ubyte,1),
               ('B',np.ubyte,1),
               ('A',np.ubyte,1)])
print(color)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


In [29]:
matrix1=np.arange(1,16).reshape(5,3)
print(matrix1)
matrix2=np.arange(7,13).reshape(3,2)
matrix=np.dot(matrix1,matrix2)
print(matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[ 58  64]
 [139 154]
 [220 244]
 [301 334]
 [382 424]]


In [30]:
data18=np.arange(1,10)
data18[(3<=data18)&(data18<=8)]*=-1
print(data18)

[ 1  2 -3 -4 -5 -6 -7 -8  9]


In [31]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [32]:
data18=np.arange(3)
print(data18**data18)
print(2<<data18>>2)
print(data18<-data18)
print(1j*data18)
print(data18/1/1)
print(data18<data18>data18)

[1 1 4]
[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [33]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array[np.nan]).astype(int).astype(float)

nan
0


C:\Users\why\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\why\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


TypeError: 'builtin_function_or_method' object is not subscriptable

In [34]:
data=np.random.uniform(-10,+10,10)
print(data)
print(np.copysign(np.ceil(np.abs(data)),data))

[-7.63821127  0.7757847   5.55946227  5.21460337 -8.83009357 -2.66121099
  8.97332234  9.02471281  9.87965486  0.65746599]
[-8.  1.  6.  6. -9. -3.  9. 10. 10.  1.]


In [35]:
data1=np.arange(1,10)
data2=np.arange(6,15)
data=np.intersect1d(data1,data2)
print(data)

[6 7 8 9]


In [37]:
defaults=np.seterr(all='ignore')
data=np.zeros(5)/0
_=np.seterr(**defaults)

In [38]:
print(np.sqrt(-1)==np.emath.sqrt(-1))

False


C:\Users\why\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


In [39]:
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
today=np.datetime64('today','D')
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print('yesterday is '+str(yesterday))
print('toady is '+str(today))
print('tomorrow is '+str(tomorrow))

yesterday is 2019-08-07
toady is 2019-08-08
tomorrow is 2019-08-09


In [40]:
data=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(data)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [41]:
A=np.ones(3)*1
B=np.ones(3)*2
C=np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [42]:
data=np.random.uniform(0,10,10)
print(data)
print(data-data%1)
print(np.trunc(data))
print(np.floor(data))
print(np.ceil(data)-1)
print(data.astype(int))

[7.72498671 7.40368346 6.2751058  1.569299   5.14017654 8.87771418
 8.34172903 4.74548011 6.05241256 3.55960619]
[7. 7. 6. 1. 5. 8. 8. 4. 6. 3.]
[7. 7. 6. 1. 5. 8. 8. 4. 6. 3.]
[7. 7. 6. 1. 5. 8. 8. 4. 6. 3.]
[7. 7. 6. 1. 5. 8. 8. 4. 6. 3.]
[7 7 6 1 5 8 8 4 6 3]


In [43]:
data=np.zeros((5,5))
data+=np.arange(0,5)
print(data)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [44]:
def generate():
    for x in range(0,10):
        yield x
data=np.fromiter(generate(),dtype=float,count=-1)
print(data)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [45]:
data=np.linspace(0,1,11,endpoint=False)[1:]
print(data)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [46]:
data=np.random.random(10)
print(data)
data.sort()
print(data)

[0.26070707 0.3867622  0.87678257 0.18831443 0.91767842 0.01791552
 0.34848502 0.70619875 0.11519993 0.78231137]
[0.01791552 0.11519993 0.18831443 0.26070707 0.34848502 0.3867622
 0.70619875 0.78231137 0.87678257 0.91767842]


In [47]:
data=np.arange(5)
np.add.reduce(data)

10

In [48]:
data1=np.random.random(5)
data2=np.random.random(5)
equal=np.allclose(data1,data2)
print(equal)

False


In [50]:
data=np.arange(5)
data.flags.writeable=False

In [51]:
data=np.random.random((10,2))
X,Y=data[:0],data[:1]
R=np.sqrt(X**2+Y**2)
T=np.arctan(2)
print(R)
print(T)

[]
1.1071487177940904


In [52]:
data=np.arange(1,10)
data[data.argmax()]=0
print(data)

[1 2 3 4 5 6 7 8 0]


In [53]:
data = np.zeros((5,5), [('x',float),('y',float)])
data['x'], data['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(data)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [54]:
data=np.arange(5)
data0=data+0.5
data1=1.0/np.subtract.outer(data,data0)
print(np.linalg.det(data1))

-131.91659501325745


In [55]:
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [62]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)
#这题不会

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

In [60]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

21
